spring.application.name=KnowThisThings
spring.mongodb.uri=mongodb+srv://souvikgta_db_user:t5xPahmueutF141w@cluster0.hccgzic.mongodb.net/knowthisthings?appName=Cluster0
spring.data.mongodb.auto-index-creation=true
server.port=8081
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG