spring:
  application:
    name: KnowThisThings
  mongodb:
    additional-hosts:
    - localhost:27017
    database: knowthisthings
  data:
      mongodb:
              auto-index-creation: true
server:
  port: 8081
# logging configuration to show the queries being executed by MongoTemplate
logging:
    level:
        org:
          springframework:
            data:
              mongodb:
                  core:
                    MongoTemplate: DEBUG